### ISSUE TITLE
SQLite3 利用時にrake redmine:plugins:migrate が失敗します

### ISSUE THREAD

**Issue by kiuchiy** [piccagliani/redmine_nikoniko_calendar2#3]
http://piccagliani.hatenablog.com/category/%E3%83%8B%E3%82%B3%E3%82%AB%E3%83%AC
を拝見して、このプラグインを知りました。

私の手元でさっそく使ってみたところ、表題のエラーが発生してしまいました。

``` ruby
Migrating redmine_nikoniko_calendar2 (Redmine Niko-niko Calendar2 plugin)...
==  CreateNikonikoHistories: migrating ========================================
-- create_table(:nikoniko_histories)
   -> 0.0462s
-- add_index(:nikoniko_histories, [:user_id, :date], {:unique=>true})
   -> 0.0008s
-- execute("ALTER TABLE nikoniko_histories ADD CONSTRAINT `fk_:nikoniko_histories_on_user_id` FOREIGN KEY (user_id) REFERENCES users(i
d) ON DELETE CASCADE")
rake aborted!
An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: near "CONSTRAINT": syntax error: ALTER TABLE nikoniko_histories ADD CONSTRAINT `fk_:nikoniko_histories_on_user_
id` FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE/home/kiuchiy/redmine-all/vendor/bundle/ruby/1.9.1/gems/sqlite3-1.3.7/
lib/sqlite3/database.rb:91:in `initialize'
/home/kiuchiy/redmine-all/vendor/bundle/ruby/1.9.1/gems/sqlite3-1.3.7/lib/sqlite3/database.rb:91:in `new'
/home/kiuchiy/redmine-all/vendor/bundle/ruby/1.9.1/gems/sqlite3-1.3.7/lib/sqlite3/database.rb:91:in `prepare'
/home/kiuchiy/redmine-all/vendor/bundle/ruby/1.9.1/gems/sqlite3-1.3.7/lib/sqlite3/database.rb:134:in `execute'
...
```

SQLite3では外部キーが使えないため、syntax error？
詳しくはまだ調べ切れていないのですが、お気づきの点がありましたら、ご指摘いただけると幸いです。

**Comment by piccagliani** [comment]
ご報告ありがとうございます。

ご指摘のとおり、

> SQLite3では外部キーが使えないため、syntax error？

が原因でした。

修正を行いましたので、再度migrationを御願いいたします。

**Comment by kiuchiy** [comment]
修正ありがとうございました。migrationできることを確認いたしました

**Comment by piccagliani** [comment]
早速のご確認、ありがとうございました。
